# Generated by Django 3.2.9 on 2022-03-20 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20220116_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='offer',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='price',
        ),
        migrations.AddField(
            model_name='destination',
            name='uploader',
            field=models.TextField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
