# Generated by Django 3.2.9 on 2022-04-02 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_destination_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='desc1',
            field=models.TextField(null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='destination',
            name='img2',
            field=models.ImageField(default=0, upload_to='pics'),
            preserve_default=False,
        ),
    ]
